site_name: GLM-py
repo_url: https://github.com/WET-tool/glm-py
repo_name: WET-tool/glm-py

theme:
    name: material
    logo: 'img/glm-icon2.png'
    custom_dir: docs/custom_theme/
    features:
      - content.code.copy
      - navigation.tabs
      - navigation.top
    palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
    - css/extra.css

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: numpy
          show_source: false


markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/"

nav:
  - Home: index.md
  - How-to: how-to.md
  - Tutorials:
    - Sparkling Lake: sparkling-lake-tutorial.md
    - Farm Dam: farm-dam-tutorial.md
  - API Reference:
    - NML: nml.md
    - Dimensions: dimensions.md
    - JSON: json-to-nml.md
    - Simulations: simulation.md
    - Inflows: inflows.md
    - Outflows: outflows.md
