site_name: GLM-py

theme:
    name: material
    logo: 'img/glm-icon2.png'
    custom_dir: custom_theme/
    features:
      - content.code.copy
    palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


extra_css:
    - css/extra.css

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: numpy
          show_source: false

markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/"

nav:
  - glm-py: index.md
  - How-to: how-to.md
  - Tutorials:
    - Sparkling Lake: sparkling-lake-tutorial.md
    - Farm Dam: farm-dam-tutorial.md
  - API Reference:
    - NML: nml.md
    - Dimensions: dimensions.md
    - JSON: json-to-nml.md
    - Simulations: simulation.md
    - Inflows: inflows.md
    - Outflows: outflows.md
