name: build-and-deploy

on:
  push:
  pull_request:
    branches:
      - executable 
  
# on:
#   push:
#     tags:
#       - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: Bundled executable and build package
      shell: bash
      run: |
        BASE_URL="https://raw.githubusercontent.com/AquaticEcoDynamics/glm-aed/main/binaries/"
        mkdir -p glmpy/bin
        if [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
          curl -L -o glmpy/bin/glm "$BASE_URL"ubuntu/22.04/glm_latest/glm""
        elif [[ "${{ matrix.os }}" == "ubuntu-20.04" ]]; then
          curl -L -o glmpy/bin/glm "$BASE_URL"ubuntu/20.04/glm_latest/glm""
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          curl -L -o glmpy/bin/glm.exe "$BASE_URL"windows/glm_latest/glm.exe""
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          curl -L -o glmpy/bin/glm "$BASE_URL"macos/Monterey/glm_latest/glm""
        fi
        chmod +x glmpy/bin/*
        python -m build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts (Ubuntu 22.04)
        uses: actions/download-artifact@v3
        with:
          name: dist-ubuntu-22.04
          path: dist/

      - name: Download Artifacts (Ubuntu 20.04)
        uses: actions/download-artifact@v3
        with:
          name: dist-ubuntu-20.04
          path: dist/

      - name: Download Artifacts (Windows)
        uses: actions/download-artifact@v3
        with:
          name: dist-windows-latest
          path: dist/

      - name: Download Artifacts (MacOS)
        uses: actions/download-artifact@v3
        with:
          name: dist-macos-latest
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://pypi.org/p/glm-py

