name: Build and Package

on:
  push:
    branches:
      - executable 

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: Bundled Executable and Build Package
      shell: bash
      run: |
        BASE_URL="https://raw.githubusercontent.com/AquaticEcoDynamics/glm-aed/main/binaries/"
        mkdir -p glmpy/bin
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          curl -L -o glmpy/bin/glm "$BASE_URL"ubuntu/22.04/glm_latest/glm""
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          curl -L -o glmpy/bin/glm.exe "$BASE_URL"windows/glm_latest/glm.exe""
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          curl -L -o glmpy/bin/glm "$BASE_URL"macos/Monterey/glm_latest/glm""
        fi
        chmod +x glmpy/bin/*
        python -m build


    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-${{ matrix.os }}
        path: dist/
