name: test-glmpy
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test-glmpy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        python -m pip install -e . --sdist
        python -m pip install pytest
    - name: Test with pytest
      run: |
        pytest