name: test-built-dist

on:
  push:
    branches: main

jobs:
  test-linux-wheels-x86_64:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version}}
    
    - name: Download files to run
      run: |
        curl https://raw.githubusercontent.com/WET-tool/glm-py/main/notebooks/glmpy-demo/run_glmpy.py --output run_glmpy.py
        curl https://raw.githubusercontent.com/WET-tool/glm-py/main/notebooks/glmpy-demo/glm3.nml --output glm3.nml
        mkdir bcs
        curl https://raw.githubusercontent.com/WET-tool/glm-py/main/notebooks/glmpy-demo/bcs/nldas_driver.csv --output bcs/nldas_driver.csv

    - name: Install glmpy
      run: |
        pip install fastapi==0.88.0
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple glm-py --use-deprecated=legacy-resolver
    
    - name: Run glmpy
      run: python run_glmpy.py
    
