name: windows-wheels

on:
  push:
    branches:
      - windows

jobs:
  build-wheel-windows:
    name: Build wheels on Windows 
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install packages and setup
        run: |
          choco install make
          choco install mingw
          choco install git
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          cd ${{ github.workspace }}
          git clone --recursive https://github.com/WET-tool/glm-aed.git
    
      - name: Compile GLM for x84_64
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/glm-aed/glm-source/ancillary/windows/Sources
          ./build_all.sh
          cd $GITHUB_WORKSPACE/glm-aed/glm-source
          ./build_glm.sh
          mkdir -p $GITHUB_WORKSPACE/glm-aed/binaries/windows
          cd $GITHUB_WORKSPACE/glm-aed/glm-source/binaries/windows
          cp -r * $GITHUB_WORKSPACE/glm-aed/binaries/windows
          cp $GITHUB_WORKSPACE/glm-aed/binaries/windows/glm.exe $GITHUB_WORKSPACE/glm/
          cd $GITHUB_WORKSPACE
          mkdir -p glmpy/bin
          sudo mv glm/glm glmpy/bin/
          sudo chmod +x glmpy/bin/*
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/glm
