name: windows-wheels

on:
  push:
    branches:
      - windows

jobs:
  build-wheel-windows:
    name: Build wheels on Wimdows 
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install packages and setup
        run: |
          choco install make
          choco install mingw
          choco install git
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          git clone --recursive https://github.com/WET-tool/glm-aed.git 
      
      - name: List root directory structure
        run: ls -R "${GITHUB_WORKSPACE}"

      - name: Compile GLM for x84_64
        run: |
          echo "Current directory: $(pwd)"
          cd D:/a/glm-py/glm-py/glm-aed/glm-source/ancillary/windows/Sources
          ./build_all.sh
          cd D:/a/glm-py/glm-py/glm-aed/glm-source
          ./build_glm.sh

          # cd ${GITHUB_WORKSPACE} 
          # mkdir -p glmpy/bin
          # cd $GITHUB_WORKSPACE/glm-source/binaries/windows
          # cp -r * $GITHUB_WORKSPACE/binaries/windows
