name: windows-wheels

on:
  push:
    branches:
      - windows

jobs:
  build-wheel-windows:
    name: Build wheels on Windows 
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install libraries
        run: .\vcpkg\vcpkg install zlib libpng freetype libgd szip curl hdf5 netcdf-c
      
      - name: Copy libraries to standard path
        run: |
          mkdir C:\lib
          xcopy /E /I .\vcpkg\installed\x64-windows\lib\* C:\lib

      - name: Copy headers to standard path
        run: |
          mkdir C:\include
          xcopy /E /I .\vcpkg\installed\x64-windows\include\* C:\include

      - name: Install packages and setup
        run: |
          choco install make
          choco install mingw
          choco install git
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          cd ${{ github.workspace }}
          git clone --recursive https://github.com/WET-tool/glm-aed.git
    
      - name: Compile GLM for x84_64
        run: |
          echo "Current directory: $(pwd)"
          cd "${env:GITHUB_WORKSPACE}\glm-aed\glm-source"
          bash ./build_glm.sh

      # - name: List root directory structure
      #   run: |
      #     ls "${env:GITHUB_WORKSPACE}"
      #     echo "GitHub workspace: ${env:GITHUB_WORKSPACE}"