name: windows-wheels

on:
  push:
    branches:
      - windows

jobs:
  build-wheel-windows:
    name: Build wheels on Wimdows
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Compile GLM for aarch64
        run: |
          git clone --recursive https://github.com/WET-tool/glm-aed.git 
          cd glm-aed/glm-source 
          mkdir binaries 
          ./build_glm.sh 
          cp /glm-aed/glm-source/binaries/glm_latest/glm /glm/ 
