name: windows-wheels

on:
  push:
    branches:
      - windows

jobs:
  build-wheel-windows:
    name: Build wheels on windows for x86_64
    runs-on: windows-2022

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install packages and setup
        run: |
          choco install make 
          choco install mingw 
          choco install git
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          git clone --recursive https://github.com/WET-tool/glm-aed.git
    
      - name: Compile GLM for x84_64
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/glm-aed/glm-source/ancillary/windows/Sources
          ./build_all.sh
          cd $GITHUB_WORKSPACE/glm-aed/glm-source
          ./build_glm.sh
          cd $GITHUB_WORKSPACE
          mkdir -p $GITHUB_WORKSPACE/glmpy/bin/
          cp "$GITHUB_WORKSPACE/glm-aed/glm-source/binaries/windows/glm_latest/glm.exe" "$GITHUB_WORKSPACE/glmpy/bin/"
          cp "$GITHUB_WORKSPACE/glm-aed/glm-source/ancillary/windows/msys/bin/"*.dll "$GITHUB_WORKSPACE/glmpy/bin/"
  
      - name: Build wheels for x86_64
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: 'cp39-* cp310-* cp311-* cp312-* pp39-* pp310-*'
          CIBW_ARCHS_WINDOWS: "x86 AMD64"
      
      - name: Upload wheels artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-windows-2022
          path: $GITHUB_WORKSPACE/wheelhouse/*.whl